### ISSUE TITLE
Let the reviewer restrt the build

### ISSUE THREAD

**Issue by hroncok** [FrostyX/fedora-review-service#15]
Apparently, as a potential reviewer, I cannot restart the build, see https://bugzilla.redhat.com/show_bug.cgi?id=2161518#c7 and below.

**Comment by FrostyX** [comment]
Hello @hroncok,
thank you for the feedback.

Related issue #11 

I intentionally put a condition into the code that only the contributor can trigger new Copr builds. But I agree that it needs to be fixed. What do you think is the best way? 

Adding a comment with new SRPM and Spec URLs (like you did) would be the most straightforward solution but I think it would cause chaos for anyone else reading the comments. Maybe it we could check if there is some other string in the comment? For example

- `[fedora-review-service-build]` - Would trigger a new build from the last sources submitted by the contributor
- `[fedora-review-service-disable]` - Would disable any further builds for this RHBZ ticket

Or any other idea?

Also, do we allow everybody to manually trigger the builds or de we limit this to contributor and assigned reviewer?

**Comment by hroncok** [comment]
> Adding a comment with new SRPM and Spec URLs (like you did) would be the most straightforward solution...

This works for local Fedora-Review (it searches for the latest comment), so packagers might be used to it.

Commands are fine, but please mention them in the comment by the bot, so they are easier to discover. Also make sure not to trigger a rebuild when the bot mentioned the commands :)

> Also, do we allow everybody to manually trigger the builds or de we limit this to contributor and assigned reviewer?

You probably want to limit the ability to Fedora packagers + the bugzilla submitter. Any one of them might need to trigger the build, but non-packagers should probably not.

Thanks for looking into this.

**Comment by FrostyX** [comment]
Thank you for the feedback,
I will implement this and other requested things early next week.

> Also make sure not to trigger a rebuild when the bot mentioned the commands :)

At least once, please. It would be so funny :smile:

**Comment by FrostyX** [comment]
> You probably want to limit the ability to Fedora packagers + the bugzilla submitter. Any one of them might need to trigger the build, but non-packagers should probably not.

I agree with this but there are technical complications in regard to figuring out who is a packager and who isn't.

- https://fasjson-client.readthedocs.io/en/latest/usage.html - is probably the way to go, but it requires authentication (kerberos principals) which is probably more time consuming task than I can afford right now.
- https://pagure.io/libpagure - this works well because you can see https://src.fedoraproject.org/group/packager without logging in. However, from the Bugzilla message, we get only an email address of a comment author. And I couldn't find any way of converting email address to FAS username.
- https://github.com/python-bugzilla/python-bugzilla - I tried also this, but when I do `bz.getuser` their groups are empty

So I will probably go the easiest route at this moment and allow anybody to trigger new builds via `[fedora-review-service-build]`. If it turns out to be problematic, I will limit it to only contributor and assignee. And when I have more time, I will figure out the kerberos principals.

**Comment by hroncok** [comment]
Makes perfect sense.

**Comment by hroncok** [comment]
Thanks.
