### ISSUE TITLE
fedora-review-service not running

### ISSUE THREAD

**Issue by mattiaverga** [FrostyX/fedora-review-service#25]
Hey, not sure if I should post this notice here or as a fedora-infra ticket... the fedora-review-service seems down since, at least, 14/5. I don't see any comment on recent package submissions.

**Comment by FrostyX** [comment]
Hello @mattiaverga,
thank you very much for the ping.

> Hey, not sure if I should post this notice here or as a fedora-infra ticket

Fedora infra folks know how to reach me so infra ticket would be fine as well. But this is probably a better place (at least at this stage).

> at least, 14/5. I don't see any comment on recent package submissions.

The service seems to be running, and I am looking through logs, and the last comment I can see is on [RHBZ 2208350](https://bugzilla.redhat.com/show_bug.cgi?id=2208350) at 2023-05-19.

Maybe some issue occurred for your tickets? Can you still find some ticket with missing comments, please?

**Comment by FrostyX** [comment]
But nevertheless, we need proper monitoring #26

**Comment by mattiaverga** [comment]
I was looking to the latest submissions in Fedora Review Stats list and, for example, these have not received the comment:
https://bugzilla.redhat.com/show_bug.cgi?id=2208805
https://bugzilla.redhat.com/show_bug.cgi?id=2208576

**Comment by FrostyX** [comment]
Sorry, it took so long to fix it. I tried few times and it always seemed to work to me.
My mistake, it only worked for tickets with already existing Copr projects.

The issue was that Fedora Review Service was trying to create new Copr projects with `fedora-36-x86_64` chroot enabled. But F36 is EOL now, so it failed.

Everything should work as expected now.
