### ISSUE TITLE
review.txt link points to wrong location and the file is empty

### ISSUE THREAD

**Issue by rathann** [FrostyX/fedora-review-service#28]
Bugzilla comments generated by f-r-s refer to wrong location for review.txt file and the actual file is empty, anyway.

Example: https://bugzilla.redhat.com/show_bug.cgi?id=2091916

Posted URL:
https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2091916-python-oscrypto/fedora-rawhide-x86_64/06126023-python-oscrypto/fedora-review/review.txt

Actual location:
https://download.copr.fedorainfracloud.org/results/%40fedora-review/fedora-review-2091916-python-oscrypto/fedora-rawhide-x86_64/06126023-python-oscrypto/python-oscrypto/review.txt
but it's empty.

**Comment by FrostyX** [comment]
Thank you very much @rathann,
this is actually a bug on the Copr side.

When you open the liked build in Copr frontend
https://copr.fedorainfracloud.org/coprs/g/fedora-review/fedora-review-2091916-python-oscrypto/build/6126023
and try to click the `review.txt` link in the Results table, it points to the wrong URL as well.

Something must have changed because a month ago, the links worked, e.g.
https://copr.fedorainfracloud.org/coprs/g/fedora-review/fedora-review-2169357-stats-collect/build/6008273/

**Comment by FrostyX** [comment]
(Probably) related fedora-review issue
https://pagure.io/FedoraReview/issue/486

**Comment by FrostyX** [comment]
WTF, why did GitHub link so many commits here.
Anyway, the issue was fixed in https://docs.pagure.org/copr.copr/release-notes/2023-08-16.html
